#%RAML 1.0 ObjectTypeDeclaration
type: object
description: A geolocation.
properties:
    latitude:
        type: number
        required: true
    longitude:
        type: number
        required: true
    altitude:
        type: number
        required: false