#%RAML 1.0 ObjectTypeDeclaration
type: object
description: A geolocation.
properties:
    latitude:
        type: number
        required: yes
    longitude:
        type: number
        required: yes
    altitude:
        type: number
        required: no