type: string
displayName: DevicePushToken
description: |
    A mobile device PUSH token, usually a three tuple <VENDOR>-<ENVIRONMENT>-<ID>:
    * VENDOR is the operating system vendor, e.g. APPLE or GOOGLE,
    * ENVIRONMENT is the push environment, e.g. SANDOX, or PRODUCTION,
    * ID is the actual token data.    
example: APPLE-PRODUCTION-1234567890
