#%RAML 1.0 Library
types:
    AnyMapping:         !include anymapping.raml
    HexColor:           !include hexcolor.raml
    KeyValue:           !include keyvalue.raml
    Location:           !include location.raml
    PushToken:          !include pushtoken.raml
    RegEx:              !include regex.raml
    StringMapping:      !include mapping.raml
    Timestamp:          !include timestamp.raml
    URL:                !include url.raml
    UVS:                !include uvs.raml
