#%RAML 1.0 Library
types:
    HexColor:   !include hexcolor.raml
    KeyValue:   !include keyvalue.raml
    Location:   !include location.raml
    Mapping:    !include mapping.raml
    Timestamp:  !include timestamp.raml
    URL:        !include url.raml
    UVS:        !include uvs.raml
